from app.views.dashboard.media.index import media
from app.views.dashboard.media.photos import media_photos
from app.views.dashboard.media.photo_activation import photo_activated
from app.views.dashboard.media.photo_delete import photo_delete
from app.views.dashboard.media.activation import media_activated
from app.views.dashboard.media.delete import media_delete
from app.views.dashboard.media.general_photo import photo_activated_general
from app.views.dashboard.media.video_delete import video_delete
from app.views.dashboard.media.video_activation import video_activated