from app.views.dashboard.items.index import items
from app.views.dashboard.items.category_activation import item_category_activated
from app.views.dashboard.items.category_delete import item_category_delete
from app.views.dashboard.items.delete import item_delete
from app.views.dashboard.items.activation import item_activated
from app.views.dashboard.items.item import item
from app.views.dashboard.items.image_activation import item_image_activated
from app.views.dashboard.items.image_delete import item_image_delete
from app.views.dashboard.items.file_delete import item_file_delete
from app.views.dashboard.items.file_activation import item_file_activated
from app.views.dashboard.items.image_category_activation import item_category_image_activated
from app.views.dashboard.items.image_general_activation import item_general_image_activated
from app.views.dashboard.items.category_is_popular import item_category_popular